# Generated by Django 5.0.4 on 2024-05-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("assunto", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Desconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=6)),
                ("data_inicial", models.DateTimeField()),
                ("data_final", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descricao", models.TextField()),
                (
                    "desconto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojaTaygra_app.desconto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojaTaygra_app.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojaTaygra_app.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="subcategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lojaTaygra_app.subcategoria",
            ),
        ),
    ]
